version: 2

#registries:
#  spring-boot-common-github-packages:
#    type: maven-repository
#    url: https://maven.pkg.github.com/ministryofjustice/laa-spring-boot-common
#    username: <your-username-here>
#    password: ${{ secrets.REPO_TOKEN }}

updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    registries: "*"
    groups:
      gradle-updates:
        exclude-patterns:
          - "uk.gov.justice.laa.springboot.ui.*"
      internal-packages:
        patterns:
          - "uk.gov.justice.laa.springboot.ui*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "**"
