services:
  laa-spring-boot-ui-template:
    build: .
    ports:
      - "8082:8082"
      - "8182:8182"
      - "5005:5005"
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
