pluginManagement {
    repositories {
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/ministryofjustice/laa-spring-boot-common")
            credentials {
                username = System.getenv("GITHUB_ACTOR")?.trim() ?: providers.gradleProperty("gpr.user").orElse("").get()
                password = System.getenv("GITHUB_TOKEN")?.trim() ?: providers.gradleProperty("gpr.key").orElse("").get()
            }
        }
        gradlePluginPortal()
        mavenCentral()
    }

    plugins {
        id 'uk.gov.laa.springboot.laa-spring-boot-gradle-plugin' version '2.2.6'
        id 'io.freefair.lombok' version '9.5.0'
        id 'com.diffplug.spotless' version '8.6.0'
        id 'com.dorongold.task-tree' version '4.0.1'
    }
}

dependencyResolutionManagement {
    repositories {
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/ministryofjustice/laa-spring-boot-common")
            credentials {
                username = System.getenv("GITHUB_ACTOR")?.trim() ?: providers.gradleProperty("gpr.user").orElse("").get()
                password = System.getenv("GITHUB_TOKEN")?.trim() ?: providers.gradleProperty("gpr.key").orElse("").get()
            }
        }
        mavenCentral()
    }
}

rootProject.name = 'laa-spring-boot-ui-template'
