server:
  port: 8082

spring:
  application:
    name: laa-spring-boot-ui-template
    version: @version@
  thymeleaf:
    cache: false

management:
  server:
    port: 8182
  endpoints:
    web:
      exposure:
        include: health

sentry:
  dsn: # configure dsn url here
  environment: # configure environment name here

logging:
  level:
    root: ${ROOT_LOGGING_LEVEL:info}
    org.springframework: ${SPRING_LOGGING_LEVEL:info}
    uk.gov.justice.laa.springboot.ui: ${APP_LOGGING_LEVEL:info}
  structured:
    format:
      console: ecs
    ecs:
      service:
        name: ${spring.application.name:default}
        version: ${spring.application.version:default}
        environment: ${spring.profiles.active:default}
        node_name: ${HOSTNAME:unknown}

---
spring:
  config:
    activate:
      on-profile: local

logging:
  level:
    root: ${ROOT_LOGGING_LEVEL:info}
    org.springframework: ${SPRING_LOGGING_LEVEL:info}
    uk.gov.justice.laa.springboot.ui: ${APP_LOGGING_LEVEL:info}
  structured:
    format:
      console:
  pattern:
    console: "%clr(%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr{faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n"
